This is makeindex, version 2.18 [MiKTeX 26.2].
Scanning style file ./TFG_FIEL_MARIBLANCA_ASIER.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file TFG_FIEL_MARIBLANCA_ASIER.acn....done (6 entries accepted, 0 rejected).
Sorting entries....done (16 comparisons).
Generating output file TFG_FIEL_MARIBLANCA_ASIER.acr....done (12 lines written, 0 warnings).
Output written in TFG_FIEL_MARIBLANCA_ASIER.acr.
Transcript written in TFG_FIEL_MARIBLANCA_ASIER.alg.
